import os
import sys
from collections import Counter
from typing import Dict, List, Optional, Sequence, Tuple

try:
    from .routine_label import (
        CSV_FIELDS,
        ClipRecord,
        RoutineConfig,
        auto_label_directory as _auto_label_directory,
        build_json_manifest as _build_json_manifest,
        build_parser,
        default_csv_path,
        default_json_path,
        default_output_dir,
        label_folder_parts,
        label_records as _label_records,
        main as _main,
        parse_clip_filename,
        read_csv,
        run as _run,
        scan_clips as _scan_clips,
        summarize_rows,
        sync_labeled_folders,
        text_to_pinyin,
        write_csv,
        write_json_manifest as _write_json_manifest,
    )
except ImportError:  # pragma: no cover - supports direct script execution
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from routine_label import (  # type: ignore
        CSV_FIELDS,
        ClipRecord,
        RoutineConfig,
        auto_label_directory as _auto_label_directory,
        build_json_manifest as _build_json_manifest,
        build_parser,
        default_csv_path,
        default_json_path,
        default_output_dir,
        label_folder_parts,
        label_records as _label_records,
        main as _main,
        parse_clip_filename,
        read_csv,
        run as _run,
        scan_clips as _scan_clips,
        summarize_rows,
        sync_labeled_folders,
        text_to_pinyin,
        write_csv,
        write_json_manifest as _write_json_manifest,
    )


ACTION_LABELS = {
    1: "01_起势",
    2: "02_左右野马分鬃",
    3: "03_白鹤亮翅",
    4: "04_左右搂膝拗步",
    5: "05_手挥琵琶",
    6: "06_左右倒卷肱",
    7: "07_左揽雀尾",
    8: "08_右揽雀尾",
    9: "09_单鞭",
    10: "10_云手",
    11: "11_单鞭",
    12: "12_高探马",
    13: "13_右蹬脚",
    14: "14_双峰贯耳",
    15: "15_转身左蹬脚",
    16: "16_左下势独立",
    17: "17_右下势独立",
    18: "18_左右穿梭",
    19: "19_海底针",
    20: "20_闪通背",
    21: "21_转身搬拦捶",
    22: "22_如封似闭",
    23: "23_十字手",
    24: "24_收势",
}

CN_NUMBERS = {
    1: "一",
    2: "二",
    3: "三",
    4: "四",
    5: "五",
    6: "六",
    7: "七",
    8: "八",
    9: "九",
    10: "十",
    11: "十一",
    12: "十二",
    13: "十三",
    14: "十四",
    15: "十五",
    16: "十六",
    17: "十七",
    18: "十八",
    19: "十九",
    20: "二十",
    21: "二十一",
    22: "二十二",
    23: "二十三",
    24: "二十四",
}


def _numbered_terms(num: int) -> List[str]:
    cn = CN_NUMBERS[num]
    suffixes = ["式", "世", "事", "时", "史", "室", "是", "示", "集"]
    return [
        *[f"第{cn}{suffix}" for suffix in suffixes],
        *[f"第{num}{suffix}" for suffix in suffixes],
        f"第{cn}个动作",
        f"第{num}个动作",
        f"第{cn}动",
        f"第{num}动",
    ]


def _rules(
    num: int,
    name: str,
    medium: Sequence[str] = (),
    fuzzy: Sequence[str] = (),
    weak: Sequence[str] = (),
) -> Dict[str, Sequence[str]]:
    return {
        "strong": [*_numbered_terms(num), name],
        "medium": list(medium),
        "fuzzy": list(fuzzy),
        "weak": list(weak),
    }


ACTION_RULES = {
    1: _rules(
        1,
        "起势",
        medium=[
            "太极起势",
            "开始动作",
            "开势",
            "起式",
            "左脚开步",
            "分脚开步",
            "分角开步",
            "两臂前举",
            "两臂前平举",
            "曲德暗掌",
            "吸气踢脚",
            "吸气提脚",
            "呼气下二",
            "稀奇开播",
            "稀奇开幕",
            "呼其落步",
            "狐雄落步",
            "奇奇上盼",
            "稀奇上旁",
        ],
        fuzzy=[
            "启势",
            "气势",
            "起式",
            "调整重心",
            "小整重心",
            "提起上抬",
            "提起上台",
            "蜥蜥上台",
            "嘻嘻上台",
            "与肩同高",
            "与间同高",
            "与监统高",
            "呼气下按",
            "呼气下安",
            "呼吸下按",
            "2B前平举",
        ],
        weak=["两脚开立", "开步", "屈膝按掌", "按掌", "起手"],
    ),
    2: _rules(
        2,
        "左右野马分鬃",
        medium=[
            "野马分鬃",
            "左野马",
            "右野马",
            "分鬃",
            "左右野马分",
            "吸气收脚转",
        ],
        fuzzy=[
            "野马分宗",
            "野马分棕",
            "野马分踪",
            "野马分钟",
            "野满分钟",
            "研磨分",
            "分宗",
            "分棕",
        ],
        weak=["抱球", "弓步分手", "上步分手", "左分手", "右分手"],
    ),
    3: _rules(
        3,
        "白鹤亮翅",
        medium=[
            "白鹤",
            "亮翅",
            "白喝两次",
            "白喝量赤",
            "白贺亮赤",
            "百赫量赤",
            "华湖亮",
            "三先将左",
        ],
        fuzzy=[
            "白鹅亮翅",
            "百合亮翅",
            "白鹤亮志",
            "白喝亮翅",
            "白喝两次",
            "白喝量赤",
            "白贺亮赤",
            "百赫量赤",
            "华湖亮",
        ],
        weak=["虚步", "右手上提", "左手下按", "起步分散", "虚步分掌"],
    ),
    4: _rules(
        4,
        "左右搂膝拗步",
        medium=[
            "搂膝拗步",
            "左搂膝",
            "右搂膝",
            "搂膝",
            "左右捞小布",
            "左右捞下腹",
            "左右捞稀澳",
            "左右捞起澳",
            "左右楼西澳",
            "做劳西奥工",
            "吸气左右捞",
        ],
        fuzzy=[
            "楼膝拗步",
            "搂膝奥步",
            "楼膝奥步",
            "左右捞小布",
            "左右捞下腹",
            "左右捞稀澳",
            "左右捞起澳",
            "左右楼西澳",
            "所有喽小腐",
            "做劳西奥工",
            "右楼小步",
            "右楼小峰",
            "左楼小宫",
            "捞手前推",
            "楼推",
            "捞手",
        ],
        weak=["搂膝推掌", "弓步推掌", "上步推掌", "上步楼推"],
    ),
    5: _rules(
        5,
        "手挥琵琶",
        medium=[
            "手挥琵琶",
            "挥琵琶",
            "琵琶",
            "手会啼啼",
            "守灰啼啼",
            "手会疲怕",
            "手归皮怕",
            "落脚合手",
        ],
        fuzzy=[
            "手挥琵把",
            "手回琵琶",
            "手挥匹帕",
            "手灰琵琶",
            "守灰琵琶",
            "手灰啼啼",
            "手会啼啼",
            "手会疲怕",
            "手归皮怕",
            "手灰啼啼",
            "疲怕",
        ],
        weak=["跟步", "虚步合手", "两手合抱"],
    ),
    6: _rules(
        6,
        "左右倒卷肱",
        medium=[
            "倒卷肱",
            "倒卷公",
            "倒撵猴",
            "倒卷弓",
            "倒卷功",
            "左右道卷工",
            "左右倒卷空",
            "诱道卷",
            "道卷",
            "撤步推",
            "撤股推",
            "屈臂撤",
            "驱逼撤",
            "吸气向后打",
            "区别退步",
        ],
        fuzzy=[
            "倒卷红",
            "倒转肱",
            "左右道卷工",
            "左右倒卷空",
            "诱道卷",
            "道卷",
            "撤步推",
            "撤股推",
            "撤破推",
            "撤不推",
            "撤不退",
            "屈臂撤",
            "驱逼撤",
            "区别退步",
        ],
        weak=["退步", "卷肱", "撤步", "推掌"],
    ),
    7: _rules(
        7,
        "左揽雀尾",
        medium=[
            "左揽雀尾",
            "左棚捋挤按",
            "左掤捋挤按",
            "灼烂却尾",
            "灼烂却味",
            "灼烂却为",
            "我懒缺位",
            "罗兰却尾",
            "吸气爆球",
        ],
        fuzzy=[
            "左懒雀尾",
            "左揽鹊尾",
            "左揽却尾",
            "灼烂却尾",
            "灼烂却味",
            "灼烂却为",
            "我懒缺位",
            "左懒雀尾",
            "罗兰却尾",
            "软体抱球",
        ],
        weak=["左掤", "左捋", "左挤", "左按", "转体抱球"],
    ),
    8: _rules(
        8,
        "右揽雀尾",
        medium=[
            "右揽雀尾",
            "右棚捋挤按",
            "右掤捋挤按",
            "又懒缺位",
            "幼兰却尾",
            "公布庞盛",
            "公布庞守",
            "吸气左脚内",
            "西七右脚内",
            "八吸气转",
            "8吸气转",
        ],
        fuzzy=[
            "右懒雀尾",
            "右揽鹊尾",
            "右揽却尾",
            "又懒缺位",
            "幼兰却尾",
            "公布庞盛",
            "公布庞守",
            "公不其安",
            "公布其案",
            "公布打击",
        ],
        weak=["右掤", "右捋", "右挤", "右按", "右臂打"],
    ),
    9: _rules(
        9,
        "单鞭",
        medium=[
            "第一遍单鞭",
            "第一个单鞭",
            "左单鞭",
            "转体越熟",
            "公布推炸",
            "扣掉白掌",
            "丁布勾手",
            "叮嘶勾手",
        ],
        fuzzy=["单边", "单编"],
        weak=["勾手", "侧弓步", "转体扣脚", "转体越熟", "公布推炸"],
    ),
    10: _rules(
        10,
        "云手",
        medium=["云手", "左右云手", "左云手", "右云手", "元首三", "云手拖掌"],
        fuzzy=["运手", "云首", "元首三", "卓云守", "又云手", "云手拖掌"],
        weak=["横步", "并步", "两手云转", "云转"],
    ),
    11: _rules(
        11,
        "单鞭",
        medium=[
            "第二遍单鞭",
            "第二个单鞭",
            "再做单鞭",
            "接单鞭",
            "勾手转体",
            "勾手推掌",
            "勾手上",
        ],
        fuzzy=["单边", "单编"],
        weak=["勾手", "侧弓步", "勾手转体", "勾手推掌", "勾手上"],
    ),
    12: _rules(
        12,
        "高探马",
        medium=[
            "高探马",
            "探马",
            "穿早上",
            "收脚和抱",
            "稀器根部翻",
            "稀奇根部翻",
            "屈臂抬",
            "虚不前退",
        ],
        fuzzy=["高叹马", "高弹马", "根部翻掌", "虚不前退", "虚不前推"],
        weak=["跟步翻掌", "虚步推掌", "右手前推", "后座提手"],
    ),
    13: _rules(
        13,
        "右蹬脚",
        medium=[
            "右蹬脚",
            "蹬脚",
            "灯角分手",
            "登脚分手",
            "登脚分掌",
            "分掌登教",
            "勾脚上灯",
        ],
        fuzzy=[
            "右登脚",
            "右灯脚",
            "右蹬腿",
            "灯角分手",
            "登脚分手",
            "登脚分掌",
            "分掌登教",
            "勾脚上灯",
            "西汽村长",
            "西齐村长",
            "稀奇川长",
            "左脚蹬脚",
            "登脚分手",
            "灯角分手",
            "村长",
            "川长",
        ],
        weak=["分手蹬脚", "提膝", "蹬出", "分掌"],
    ),
    14: _rules(
        14,
        "双峰贯耳",
        medium=[
            "双峰贯耳",
            "双峰",
            "贯耳",
            "双风罐",
            "双逢冠",
            "双风惯耳",
            "双风逛儿",
            "根部报首",
            "稀奇公布",
        ],
        fuzzy=[
            "双风贯耳",
            "双峰灌耳",
            "双拳贯耳",
            "双风罐",
            "双逢冠",
            "双风惯耳",
            "双风逛儿",
            "公布冠权",
            "公布冠缺",
            "公布冠",
        ],
        weak=["双拳", "两拳", "弓步贯拳", "贯拳"],
    ),
    15: _rules(
        15,
        "转身左蹬脚",
        medium=["左蹬脚", "转身蹬脚", "转身左蹬"],
        fuzzy=["左登脚", "左灯脚", "转身左蹬腿", "转身左灯角", "左灯角"],
        weak=["转身", "左脚蹬出", "提膝蹬脚"],
    ),
    16: _rules(
        16,
        "左下势独立",
        medium=[
            "左下势独立",
            "左下势",
            "左独立",
            "下势独立",
            "下市独",
            "下世独",
            "下是独",
            "一十六十",
            "驱敦开步",
            "屈腿开步",
        ],
        fuzzy=[
            "左下式独立",
            "左下势杜立",
            "左下是独立",
            "左下是足利",
            "左下是",
            "下市独",
            "下世独",
            "下是独",
            "一十六十",
        ],
        weak=["仆步", "左独立步", "挑掌", "收脚勾手"],
    ),
    17: _rules(
        17,
        "右下势独立",
        medium=[
            "右下势独立",
            "右下势",
            "右独立",
            "下势独立",
            "右下是独立",
            "右下是",
            "又下石都没",
            "又下石头岭",
            "又下时都没",
            "又下石毒力",
            "五呼气独",
        ],
        fuzzy=[
            "右下式独立",
            "右下势杜立",
            "右下是独立",
            "又下石都没",
            "又下石头岭",
            "又下时都没",
            "又下石毒力",
            "又下次",
        ],
        weak=["仆步", "右独立步", "挑掌", "独立调整"],
    ),
    18: _rules(
        18,
        "左右穿梭",
        medium=[
            "左右穿梭",
            "穿梭",
            "玉女穿梭",
            "左右传说",
            "公布又参说",
            "上部拖掌",
            "上不脱",
        ],
        fuzzy=[
            "左右穿说",
            "左右传说",
            "左右穿缩",
            "左右参说",
            "左右有才说",
            "玉女穿缩",
            "公布又参说",
            "左穿梭",
            "穿著",
        ],
        weak=["架推掌", "斜方推掌", "上步架掌", "公布假推"],
    ),
    19: _rules(
        19,
        "海底针",
        medium=[
            "海底针",
            "还抵真",
            "虚不叉",
            "虚步叉",
            "虚不察长",
            "虚不叉仗",
            "一十九十",
            "落脚插掌",
        ],
        fuzzy=["海底真", "海底珍", "还抵真", "虚不叉", "虚步叉", "识不察"],
        weak=["插掌", "虚步插掌", "向下插", "提手收脚"],
    ),
    20: _rules(
        20,
        "闪通背",
        medium=["闪通背", "闪通臂", "闪通币", "散通壁", "上部架"],
        fuzzy=["闪通被", "闪同背", "闪通币", "散通壁"],
        weak=["弓步推掌", "上步撑掌", "架掌前推"],
    ),
    21: _rules(
        21,
        "转身搬拦捶",
        medium=[
            "搬拦捶",
            "转身搬拦",
            "搬拦锤",
            "转身斑斓",
            "百步搬圈",
            "百步奔全",
            "白布班群",
            "做腿收拳",
            "上部拦掌",
        ],
        fuzzy=[
            "搬兰捶",
            "搬拦垂",
            "搬拦锤",
            "搬篮锤",
            "转身斑斓",
            "百步搬圈",
            "百步奔全",
            "白布班群",
            "白角翻手",
        ],
        weak=["搬拳", "拦掌", "打拳", "进步栽捶", "上步拦"],
    ),
    22: _rules(
        22,
        "如封似闭",
        medium=[
            "如封似闭",
            "如封似",
            "封似闭",
            "如风似壁",
            "如风势毙",
            "路逢四壁",
            "呼气下岸前",
        ],
        fuzzy=["如风似闭", "如封四闭", "如风四闭", "如风似壁", "如风势毙", "路逢四壁"],
        weak=["后坐", "收掌", "按掌", "双手前按"],
    ),
    23: _rules(
        23,
        "十字手",
        medium=["十字手", "十字", "战力十字手", "交叉搭手", "交叉八手", "右臂打开"],
        fuzzy=["十字首", "十字守", "战力十字手", "交叉搭手", "交叉八手"],
        weak=["两手交叉", "合抱", "开立步", "双手合抱"],
    ),
    24: _rules(
        24,
        "收势",
        medium=[
            "收式",
            "结束动作",
            "收尾",
            "并不怀缘",
            "并无怀缘",
            "并还原",
            "还原归正",
            "还原规证",
            "收小并拢还",
            "收右脚",
            "收左脚",
        ],
        fuzzy=[
            "收拾",
            "手势",
            "收视",
            "并不怀缘",
            "并无怀缘",
            "并还原",
            "还原归正",
            "还原规证",
            "收小并拢还",
            "分掌分手",
            "翻掌分手",
            "反掌分手",
            "柔戏霞",
            "凤希霞",
            "土气侠",
        ],
        weak=["还原", "并步", "两手下落", "自然站立"],
    ),
}

OPENING_RULES = {
    "strong": ["二十四式太极拳", "24式太极拳", "简化太极拳"],
    "medium": ["太极拳", "二十四式", "24式", "教学", "演示", "分解", "预备"],
    "fuzzy": ["太极", "太级", "二十式"],
    "weak": ["大家", "今天", "练习", "开始"],
}

CLOSING_IRRELEVANT_RULES = {
    "strong": ["谢谢观看", "感谢观看", "下次见", "再见"],
    "medium": ["关注", "点赞", "订阅", "评论区", "今天的视频", "今天的练习"],
    "fuzzy": ["欢迎大家", "希望大家", "我们下期"],
    "weak": ["谢谢", "视频", "练习"],
}

TAIJI24_CONFIG = RoutineConfig(
    name="taiji24",
    action_labels=ACTION_LABELS,
    action_rules=ACTION_RULES,
    intro_label=None,
    outro_label=None,
    intro_outro_rules=OPENING_RULES,
    closing_irrelevant_rules=CLOSING_IRRELEVANT_RULES,
    description="Generate reviewable CSV labels and folders for 24-form Taijiquan clips.",
)


def scan_clips(input_dir: str) -> List[ClipRecord]:
    return _scan_clips(
        input_dir,
        action_rules=TAIJI24_CONFIG.action_rules,
        intro_outro_rules=TAIJI24_CONFIG.intro_outro_rules,
    )


def label_records(records: Sequence[ClipRecord]) -> List[Dict[str, str]]:
    return _label_records(records, TAIJI24_CONFIG)


def auto_label_directory(input_dir: str) -> List[Dict[str, str]]:
    return _auto_label_directory(input_dir, TAIJI24_CONFIG)


def build_json_manifest(
    rows: Sequence[Dict[str, str]],
    input_dir: str,
    csv_path: Optional[str] = None,
    output_dir: Optional[str] = None,
) -> Dict[str, object]:
    return _build_json_manifest(
        rows,
        input_dir,
        config=TAIJI24_CONFIG,
        csv_path=csv_path,
        output_dir=output_dir,
    )


def write_json_manifest(
    rows: Sequence[Dict[str, str]],
    json_path: str,
    input_dir: str,
    csv_path: Optional[str] = None,
    output_dir: Optional[str] = None,
) -> None:
    _write_json_manifest(
        rows,
        json_path,
        input_dir,
        config=TAIJI24_CONFIG,
        csv_path=csv_path,
        output_dir=output_dir,
    )


def run(
    input_dir: str,
    csv_path: Optional[str] = None,
    json_path: Optional[str] = None,
    output_dir: Optional[str] = None,
    copy_files: bool = True,
    write_json_file: bool = True,
    force: bool = False,
    move: bool = False,
    dry_run: bool = False,
    clean_output: bool = False,
) -> Tuple[List[Dict[str, str]], Counter]:
    return _run(
        input_dir,
        config=TAIJI24_CONFIG,
        csv_path=csv_path,
        json_path=json_path,
        output_dir=output_dir,
        copy_files=copy_files,
        write_json_file=write_json_file,
        force=force,
        move=move,
        dry_run=dry_run,
        clean_output=clean_output,
    )


def main() -> None:
    _main(TAIJI24_CONFIG)


if __name__ == "__main__":
    main()
